pipeline {
    agent any

   
        stage('Build') {
            steps {
                 {
                sh 'mvn -B -DskipTests clean package'
                }
            
            }
        }
     
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   } 
}
